-- db/migration/V1__create_r2p_transactions_table.sql
CREATE TABLE IF NOT EXISTS r2p_transactions
(
    id                          BIGSERIAL PRIMARY KEY,
    payment_request_id          VARCHAR(35) NOT NULL UNIQUE,
    end_to_end_id               VARCHAR(35) NOT NULL,
    request_message_id          VARCHAR(35),
    response_message_id         VARCHAR(35),
    transaction_status          VARCHAR(10) NOT NULL,
    use_case                    VARCHAR(10) NOT NULL,
    product                     VARCHAR(10) NOT NULL,
    requested_amount            DECIMAL(19, 2),
    requested_amount_currency   VARCHAR(3),
    accepted_amount             DECIMAL(19, 2),
    accepted_amount_currency    VARCHAR(3),
    creditor_agent_id           VARCHAR(35),
    debtor_agent_id             VARCHAR(35),
    creditor_alias              VARCHAR(35),
    debtor_alias                VARCHAR(35),
    creditor_alias_type         VARCHAR(10),
    debtor_alias_type           VARCHAR(10),
    due_date                    TIMESTAMP,
    request_reason              TEXT,
    message                     TEXT,
    settlement_details_json     TEXT,
    original_payment_request_id VARCHAR(35),
    is_refund                   BOOLEAN              DEFAULT FALSE,
    created_at                  TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMP   NOT NULL DEFAULT NOW(),
    version                     BIGINT               DEFAULT 0,

    INDEX                       idx_payment_request_id(payment_request_id),
    INDEX                       idx_end_to_end_id(end_to_end_id),
    INDEX                       idx_transaction_status(transaction_status),
    INDEX                       idx_creditor_agent_id(creditor_agent_id),
    INDEX                       idx_debtor_agent_id(debtor_agent_id),
    INDEX                       idx_created_at(created_at),
    INDEX                       idx_due_date(due_date),
    INDEX                       idx_original_payment_request_id(original_payment_request_id)
);